
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/Diplom
spring.datasource.username=postgres
spring.datasource.password=qwerty1963.

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=false

app.upload.dir=uploads

spring.web.resources.static-locations=classpath:/static/

logging.level.org.springframework.security=INFO

server.address=0.0.0.0